title: GU18
author: geese
email: loosey@goosey.edu
description: > # this means to ignore newlines until "baseurl:"
  Are there Avacados? I think so  
  
  _it's for the shirts_
  
# social links
twitter_username: gosose
github_username:  jdlonergan08

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
