title: GU
author: David Lonergan
email: j.david.lonergan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Are there avacados? I think so. Buy some shirts 

# social links
twitter_username: no need 
github_username:  jdlonergan08

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-tactile
